# Generated by Django 5.1.6 on 2025-03-03 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.URLField(max_length=300)),
                ('features', models.TextField(max_length=500)),
                ('used_technology', models.CharField(max_length=400)),
                ('github_link', models.URLField(max_length=300)),
                ('live_link', models.URLField(max_length=300)),
            ],
        ),
    ]
