# Generated by Django 5.1.6 on 2025-03-04 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0004_academic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='academic',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='academic',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
