# Generated by Django 5.1.6 on 2025-03-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0005_alter_academic_options_academic_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('displayed_in', models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th')], max_length=10)),
                ('category', models.CharField(max_length=50)),
                ('icon', models.CharField(max_length=20)),
                ('items', models.CharField(max_length=250)),
            ],
            options={
                'ordering': ['displayed_in'],
            },
        ),
        migrations.AlterModelOptions(
            name='academic',
            options={'ordering': ['-created_at']},
        ),
    ]
