# Generated by Django 5.1.6 on 2025-03-04 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port_folio', '0006_skill_alter_academic_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='displayed_in',
            field=models.CharField(choices=[('1', '1st'), ('2', '2nd'), ('3', '3rd'), ('4', '4th'), ('5', '5th')], max_length=10, unique=True),
        ),
    ]
